# HoloTopography конфигурация

# Настройки отображения
defaultSize: 30.0     # Размер карты по умолчанию (в блоках)
maxSize: 50.0         # Максимальный размер карты (в блоках)
updateInterval: 5     # Интервал обновления карты (в тиках)
particlesPerChunk: 25 # Плотность частиц (1-100)
particleSize: 1.2     # Размер частиц (0.5-2.0)

# Производительность
particleRenderDistance: 80.0  # Максимальная дистанция рендеринга частиц от игрока
limitParticles: true  # Ограничивать количество частиц для производительности

# Частицы
particleHeight: 1.0   # Высота над блоком для отображения частиц

# Отладка
debug: true  # Включить отладочные сообщения
